### ISSUE TITLE
invalid link

### ISSUE THREAD

**Issue by kurnon** [nimasmi/MMM-repeating-schedule#1]
I am a noob but I think the link in your documentation to install is incorrect

git clone git@github.com:nimasmi/MMM-repeating-schedule.git

it should be 
git clone https://github.com/nimasmi/MMM-repeating-schedule.git

**Comment by nimasmi** [comment]
You are partially right. The git@github link will work if you are logged into GitHub in your shell, i.e. by having uploaded your public SSH key to GitHub, and configuring the private key locally in your SSH client or shell.

On the other hand, the https link works without being logged in, so I'll update the instructions. Thanks!

**Comment by kurnon** [comment]
Thanks, I wasn't sure, but I thought it would help others.

On a side note, where should the var (array) lines go? I get errors when trying to add them to my config file.

**Comment by nimasmi** [comment]
As you may guess from the age of this repository, I haven't used this for a few years. I think I had them at the top of my config file. They can be anywhere that is imported and makes the variables valid when you refer to them in the `dates` object.
